---
kind: pipeline
type: kubernetes
name: default

concurrency:
  limit: 1

steps:
  - name: test
    image: node:10.15
    environment:
      AUTH0_DOMAIN:
        from_secret: auth0_test_domain
      AUTH0_CLIENT_ID:
        from_secret: auth0_test_client_id
      AUTH0_CLIENT_SECRET:
        from_secret: auth0_test_client_secret
      AUTH0_EXTENSION_URL:
        from_secret: auth0_test_extension_url
    commands:
    - npm install
    - npm test

  - name: build + publish
    image: node:10.15
    commands:
    - npm run build
    - echo "@cyrus:registry=https://us-npm.pkg.dev/cyrus-containers/levitate-npm/" > .npmrc
    - echo "//us-npm.pkg.dev/cyrus-containers/levitate-npm/:always-auth=true" >> .npmrc
    - npm run artifactregistry-login
    - npm publish --access public
    when:
      branch:
      - master

trigger:
  event:
    include:
    - push
